#!/bin/bash

############################################################################################
# Submit this script as a job using:
# qsub stacks_populations_denovo.job
############################################################################################

#PBS -l select=2:ncpus=24:mpiprocs=24
#PBS -P CBBI1682
#PBS -q normal
#PBS -l walltime=1:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/stacksoutput_denovo/denovopops_stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/stacksoutput_denovo/denovopops_stderr.txt
#PBS -N stacks_populations_denovo
#PBS -M vsteenderen@gmail.com
#PBS -m abe

##############################################################

module add chpc/BIOMODULES
module add stacks

BASE_DIR="/mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata"
cd "$BASE_DIR"

# get the output file populations.sumstats.tsv from the first denovo run, and extract 1000 random loci from it
# Note: this sumstats file is written after the first time denovo_map.pl is run. You can use it to create the whitelist, but it isn't important thereafter,
# since every time the populations program is run, it will create a sumstats file for that run 
# 1000 loci is a manageable amount of data for STRUCTURE. Not sure whether STRUCTURE is that useful if it is limited by the amount of data it can handle?
# the output file is whitelist.tsv 
grep -v "^#" ./stacksoutput_denovo/populations.sumstats.tsv | cut -f 1 | sort | uniq | shuf -n 1000 | sort -n > ./stacksoutput_denovo/whitelist.tsv

##############################################################
# Run populations 
##############################################################

##############################################
# RUN USING BROAD GROUPINGS FOR LOCALITY
##############################################

mkdir -p ./stacksoutput_denovo/populations/broadgroups/structure
mkdir -p ./stacksoutput_denovo/populations/broadgroups/otherformats

# run populations to create output in the right format for use in STRUCTURE
populations -P ./stacksoutput_denovo/ -O ./stacksoutput_denovo/populations/broadgroups/structure --popmap ./barcodes/bothplates_pops.txt -r 0.75 -f p_value -t 12 --hwe --fstats --structure --write-single-snp --ordered-export -W ./stacksoutput_denovo/whitelist.tsv
# run populations again to create other output formats, without the whitelist option (i.e. run on all the loci)
populations -P ./stacksoutput_denovo/ -O ./stacksoutput_denovo/populations/broadgroups/otherformats --popmap ./barcodes/bothplates_pops.txt -r 0.75 -f p_value -t 12 --hwe --fstats --genepop --plink --phylip --vcf --vcf-all

#############################################################
# RUN USING GROUPS SUBDIVIDED INTO DIFFERENT SOUTH AFRICAN LOCATIONS
#############################################################

# Change the folder name here as appropriate, or comment out if not needed

mkdir -p ./stacksoutput_denovo/populations/SAspecific/structure
mkdir -p ./stacksoutput_denovo/populations/SAspecific/otherformats

# run populations to create output in the right format for use in STRUCTURE
populations -P ./stacksoutput_denovo/ -O ./stacksoutput_denovo/populations/SAspecific/structure --popmap ./barcodes/bothplates_pops_SA.txt -r 0.75 -f p_value -t 12 --hwe --fstats --structure --write-single-snp --ordered-export -W ./stacksoutput_denovo/whitelist.tsv
# run populations again to create other output formats, without the whitelist option (i.e. run on all the loci)
populations -P ./stacksoutput_denovo/ -O ./stacksoutput_denovo/populations/SAspecific/otherformats --popmap ./barcodes/bothplates_pops_SA.txt -r 0.75 -f p_value -t 12 --hwe --fstats --genepop --plink --phylip --vcf --vcf-all