#!/bin/bash

############################################################################################
# Submit this script as a job using:
# qsub stacks_populations_denovo.job
############################################################################################

#PBS -l select=2:ncpus=24:mpiprocs=24
#PBS -P CBBI1682
#PBS -q normal
#PBS -l walltime=3:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace/stacksoutput_denovo/denovopops_stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace/stacksoutput_denovo/denovopops_stderr.txt
#PBS -N stacks_populations_denovo
#PBS -M vsteenderen@gmail.com
#PBS -m abe

##############################################################

module add chpc/BIOMODULES
module add stacks

BASE_DIR="/mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace"
cd "$BASE_DIR"

##############################################################
# Run populations 
##############################################################

##############################################
# RUN USING BROAD GROUPINGS FOR LOCALITY
##############################################

mkdir -p "$BASE_DIR/stacksoutput_denovo/populations/broadgroups/structure"
mkdir -p "$BASE_DIR/stacksoutput_denovo/populations/broadgroups/otherformats"

# run populations to create output in the right format for use in STRUCTURE
populations -P "$BASE_DIR/stacksoutput_denovo" -O "$BASE_DIR/stacksoutput_denovo/populations/broadgroups/structure" --popmap "$BASE_DIR/barcodes/bothplates_pops.txt" -r 0.75 -f p_value -t 12 --hwe --fstats --structure --write-single-snp
# run populations again to create other output formats, without the whitelist option (i.e. run on all the loci)
populations -P "$BASE_DIR/stacksoutput_denovo" -O "$BASE_DIR/stacksoutput_denovo/populations/broadgroups/otherformats" --popmap "$BASE_DIR/barcodes/bothplates_pops.txt" -r 0.75 -f p_value -t 12 --hwe --fstats --genepop --plink --phylip --vcf --vcf-all

#############################################################
# RUN USING GROUPS SUBDIVIDED INTO FINER RESOLUTION LOCATIONS
#############################################################

# Change the folder name here as appropriate, or comment out if not needed

#mkdir -p "$BASE_DIR/stacksoutput_denovo/populations/finescale_groups/structure"
#mkdir -p "$BASE_DIR/stacksoutput_denovo/populations/finescale_groups/otherformats"

# run populations to create output in the right format for use in STRUCTURE
#populations -P "$BASE_DIR/stacksoutput_denovo" -O "$BASE_DIR/stacksoutput_denovo/populations/finescale_groups/structure" --popmap "$BASE_DIR/barcodes/bothplates_pops_finergrouping.txt" -r 0.75 -f p_value -t 12 --hwe --fstats --structure --write-single-snp --ordered-export

# run populations again to create other output formats
# change the barcode/pops file to the one with another grouping approach
#populations -P "$BASE_DIR/stacksoutput_denovo" -O "$BASE_DIR/stacksoutput_denovo/populations/finescale_groups/otherformats" --popmap "$BASE_DIR/barcodes/bothplates_pops_finergrouping.txt" -r 0.75 -f p_value -t 12 --hwe --fstats --genepop --plink --phylip --vcf --vcf-all
