#!/bin/bash

#PBS -l select=2:ncpus=24
#PBS -P CBBI1682
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -o /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace/stacksoutput_denovo/gstacks_stdout.txt
#PBS -e /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace/stacksoutput_denovo/gstacks_sterr.txt
#PBS -N gstacks
#PBS -M vsteenderen@gmail.com
#PBS -m abe

module add chpc/BIOMODULES 
module add stacks 

cd /mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace/stacksoutput_denovo

BASE_DIR="/mnt/lustre/users/cvansteenderen/RADseq_nodiflorum/rawdata/basespace"

gstacks -P "$BASE_DIR/stacksoutput_denovo" --threads 24 -M "$BASE_DIR/barcodes/bothplates_pops.txt"